In [3]:
import numpy as np

In [19]:
arr = np.array([[1,2],[2,1],[1,1,]],dtype = float, ndmin = 2)
print(arr)

[[1. 2.]
 [2. 1.]
 [1. 1.]]


Create a Numpy Array that contains exactly 20 values evenly spaced from -1.0 to 1.0 inclusive.

In [44]:
err = np.linspace(-1,1,20)
print(err)

[-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]


In [58]:
a1 = np.array([[1,2,3],[4,5,6]])
a1[1,2]


6

In [74]:
a1 = np.array([[1,2,3],[4,5,6]])
a1[0:2,1:2]



array([[2],
       [5]])

 Example 2: 

In [90]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,12]])
arr2 = arr1 + 1
print(arr2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [ 2  3 13]]


Example 3:

In [102]:
arr2 = arr1[-1] * 5
arr2


array([ 5, 10, 60])

In [106]:
arr3 = arr2.copy()
arr3


array([ 5, 10, 60])

In [108]:
arr4 = arr3.reshape(3,1)
arr4

array([[ 5],
       [10],
       [60]])

In [174]:
arr1 = np.random.random((3,4))
arr1

array([[0.85851333, 0.0591563 , 0.98222809, 0.86500924],
       [0.71711718, 0.56823941, 0.16454823, 0.26653598],
       [0.65525973, 0.39573076, 0.91162973, 0.15367719]])

In [118]:
arr2 = np.linspace(10,20,12)
arr2

array([10.        , 10.90909091, 11.81818182, 12.72727273, 13.63636364,
       14.54545455, 15.45454545, 16.36363636, 17.27272727, 18.18181818,
       19.09090909, 20.        ])

In [120]:
arr2 = arr2.reshape(3,4)
arr2

array([[10.        , 10.90909091, 11.81818182, 12.72727273],
       [13.63636364, 14.54545455, 15.45454545, 16.36363636],
       [17.27272727, 18.18181818, 19.09090909, 20.        ]])

In [180]:
arr3 = arr1 + arr2
arr3
arr3[0:3,0:1]

array([[10.85851333],
       [14.35348081],
       [17.92798701]])

In [194]:
a1 = np.array([[1,2,3,4,5],[3,3,4,1,2]]) 
a1[(a1 != 3) & (a1 != 4)]

array([1, 2, 5, 1, 2])

Lecture 10 Example 4

In [198]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,12]])

In [202]:
arr1[(arr1>2) & (arr1<9)]

array([3, 4, 5, 6, 7, 8])

In [25]:
arr = np.arange(0,20,3)
arr[(arr != 3) & (arr <12)]

array([0, 6, 9])

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6])

ValueError: cannot reshape array of size 6 into shape (4,4)