In [7]:
import numpy as np


Lecture 11 Example 1

In [5]:
a1 = np.array([[1,2,3,4,5],[3,3,4,1,2]])

In [13]:
a2 = a1[a1 != 3]
a2

array([1, 2, 4, 5, 4, 1, 2])

In [11]:
a3 = a1[a1 % 2 == 0 ]
a3

array([2, 4, 4, 2])

In [9]:
import numpy as np
a1 = np.array([[1,2,3,4,5],[3,3,4,1,2]])
#a4 = a1[a1 % 2 ==0 and a1 > 3] # incorrect
a4 = a1[(a1 % 2 == 0) & (a1 > 3)]
a4



array([4, 4])